package com.jschool.controllers.exception;

/**
 * Created by infinity on 19.02.16.
 */
public enum  ControllerStatusCode {

    PAGE_NOT_FOUND,
    EMPTY_FIELDS,EMAIL_FORMAT,ORDER_NUMBER_FORMAT,CARGO_NUMBER_FORMAT,CARGO_WEIGHT_FORMAT,
    DRIVER_NUMBER_FORMAT,TRUCK_NUMBER_FORMAT,TRUCK_CAPACITY_FORMAT,TRUCK_SHIFT_FORMAT,
    WRONG_EMAIL_OR_PASS, WRONG_DRIVER, UNDEFINED_LOGIN
}
